services:
  _defaults:
    autowire: true
    public: false
  OxidEsales\EshopCommunity\Internal\Logger\Validator\LoggerConfigurationValidatorInterface:
    class: OxidEsales\EshopCommunity\Internal\Logger\Validator\PsrLoggerConfigurationValidator
    public: true
  OxidEsales\EshopCommunity\Internal\Logger\Configuration\MonologConfigurationInterface:
    class: OxidEsales\EshopCommunity\Internal\Logger\Configuration\MonologConfiguration
    arguments:
      $loggerName: 'OXID Logger'
      $logFilePath: '@utility.context.get_log_file_path'
      $logLevel: '@utility.context.get_log_level'
  OxidEsales\EshopCommunity\Internal\Logger\Factory\LoggerFactoryInterface:
    class: OxidEsales\EshopCommunity\Internal\Logger\Factory\MonologLoggerFactory
  Monolog\Logger:
    class: Monolog\Logger
    factory: 'OxidEsales\EshopCommunity\Internal\Logger\Factory\LoggerFactoryInterface:create'
  Psr\Log\LoggerInterface:
    class: OxidEsales\EshopCommunity\Internal\Logger\Wrapper\LoggerWrapper
    arguments:
      $logger: '@Monolog\Logger'
    public: true
  utility.context.get_log_file_path:
    class: OxidEsales\EshopCommunity\Internal\Utility\ContextInterface
    factory: OxidEsales\EshopCommunity\Internal\Utility\ContextInterface:getLogFilePath
  utility.context.get_log_level:
    class: OxidEsales\EshopCommunity\Internal\Utility\ContextInterface
    factory: OxidEsales\EshopCommunity\Internal\Utility\ContextInterface:getLogLevel